name: Address Data Update Workflow 

on:
  push:
    paths:
      - 'data_upload/address*.csv'
      - 'requirements.txt' # Track changes to your requirements file

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2 
      - name: Install R Dependencies (if needed)
        if: ${{ hashFiles('requirements.txt') != '' }} # Install only if requirements.txt has changed
        run: Rscript -e 'install.packages(c("tidyverse","gridExtra","RSQLite","lubridate"))'
      - name: Run Data Update Script
        run: |
          Rscript R/update_data.R
          if [[ $$? -ne 0 ]]; then exit 1; fi # Check for errors in update_data.R
        env:
          GITHUB_TOKEN: ${{ secrets.NEW_REPO_TOKEN }} 